-- Somente consultas. Execute com F5 como MEDISTOCK.
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
    IF SYS_CONTEXT('USERENV', 'SESSION_USER') <> 'MEDISTOCK'
       OR SYS_CONTEXT('USERENV', 'CON_NAME') <> 'FREEPDB1' THEN
        RAISE_APPLICATION_ERROR(-20090,
            'Execute este arquivo na conexao MEDISTOCK do FREEPDB1.');
    END IF;
END;
/

PROMPT Conexao atual: esperado MEDISTOCK / FREEPDB1
SELECT USER AS USUARIO, SYS_CONTEXT('USERENV', 'CON_NAME') AS BANCO FROM DUAL;

PROMPT Seis tabelas esperadas
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;

PROMPT Contagens esperadas apos a carga inicial
SELECT 'HOSPITAIS' AS TABELA, COUNT(*) AS REGISTROS, 3 AS ESPERADO FROM HOSPITAIS
UNION ALL SELECT 'ITENS_ESTOQUE', COUNT(*), 12 FROM ITENS_ESTOQUE
UNION ALL SELECT 'HISTORICO_CONSUMO', COUNT(*), 72 FROM HISTORICO_CONSUMO
UNION ALL SELECT 'ENTREGAS', COUNT(*), 4 FROM ENTREGAS
UNION ALL SELECT 'TRANSFERENCIAS', COUNT(*), 4 FROM TRANSFERENCIAS
UNION ALL SELECT 'USUARIOS', COUNT(*), 0 FROM USUARIOS;

PROMPT Procedure: esperado VALID
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'PROCEDURE' ORDER BY OBJECT_NAME;

PROMPT Erros de compilacao: esperado nenhuma linha
SELECT NAME, TYPE, LINE, POSITION, TEXT FROM USER_ERRORS ORDER BY NAME, SEQUENCE;

PROMPT Relacionamentos: esperado oito FKs habilitadas
SELECT TABLE_NAME, CONSTRAINT_NAME, STATUS
FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R'
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

PROMPT Inventario com nivel calculado como na entidade Java
SELECT i.ID, i.NOME, h.NOME AS HOSPITAL,
       i.QUANTIDADE_ATUAL, i.QUANTIDADE_MINIMA,
       CASE WHEN i.QUANTIDADE_ATUAL <= i.QUANTIDADE_MINIMA THEN 'CRITICO'
            WHEN i.QUANTIDADE_ATUAL <= i.QUANTIDADE_MINIMA * 1.5 THEN 'ATENCAO'
            ELSE 'NORMAL' END AS NIVEL,
       i.VALIDADE
FROM ITENS_ESTOQUE i JOIN HOSPITAIS h ON h.ID = i.HOSPITAL_ID
ORDER BY h.ID, i.ID;

PROMPT Dicionario fisico do schema
SELECT TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE,
       CHAR_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, IDENTITY_COLUMN
FROM USER_TAB_COLUMNS ORDER BY TABLE_NAME, COLUMN_ID;
