SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
    IF SYS_CONTEXT('USERENV', 'SESSION_USER') <> 'MEDISTOCK'
       OR SYS_CONTEXT('USERENV', 'CON_NAME') <> 'FREEPDB1' THEN
        RAISE_APPLICATION_ERROR(-20090,
            'Execute este arquivo na conexao MEDISTOCK do FREEPDB1.');
    END IF;
END;
/

CREATE TABLE IF NOT EXISTS ALERTAS (
    ID NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ITEM_ESTOQUE_ID NUMBER(19,0),
    HOSPITAL_ID NUMBER(19,0),
    TIPO VARCHAR2(20 CHAR) NOT NULL,
    MENSAGEM VARCHAR2(400 CHAR) NOT NULL,
    ORIGEM VARCHAR2(150 CHAR),
    CRIADO_EM TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERTAS PRIMARY KEY (ID),
    CONSTRAINT CK_ALERTA_TIPO CHECK (TIPO IN ('CRITICO','ATENCAO','INFO')),
    CONSTRAINT FK_ALERTA_ITEM FOREIGN KEY (ITEM_ESTOQUE_ID) REFERENCES ITENS_ESTOQUE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ALERTA_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAIS(ID)
);

COMMENT ON TABLE ALERTAS IS 'Alertas de estoque e validade gravados pela procedure prc_registrar_alertas_criticos.';
COMMENT ON COLUMN ALERTAS.ID IS 'Chave primária; gerada pelo Oracle.';
COMMENT ON COLUMN ALERTAS.ITEM_ESTOQUE_ID IS 'FK para ITENS_ESTOQUE.ID; o alerta é removido junto com o item.';
COMMENT ON COLUMN ALERTAS.HOSPITAL_ID IS 'FK para HOSPITAIS.ID; hospital do item no momento do alerta.';
COMMENT ON COLUMN ALERTAS.TIPO IS 'CRITICO, ATENCAO ou INFO.';
COMMENT ON COLUMN ALERTAS.MENSAGEM IS 'Texto do alerta com os valores do momento em que foi gerado.';
COMMENT ON COLUMN ALERTAS.ORIGEM IS 'Local de armazenamento do item.';
COMMENT ON COLUMN ALERTAS.CRIADO_EM IS 'Data e hora em que o alerta foi gravado.';

CREATE INDEX IF NOT EXISTS IX_ALERTA_ITEM_DATA ON ALERTAS (ITEM_ESTOQUE_ID, CRIADO_EM);
CREATE INDEX IF NOT EXISTS IX_ALERTA_HOSPITAL ON ALERTAS (HOSPITAL_ID);

CREATE OR REPLACE VIEW vw_alertas_vigentes AS
SELECT item_estoque_id, item_nome, hospital_id, hospital_nome,
       tipo, mensagem, local_armazenamento, criado_em
  FROM (
        SELECT a.item_estoque_id,
               ie.nome                AS item_nome,
               h.id                   AS hospital_id,
               h.nome                 AS hospital_nome,
               a.tipo,
               a.mensagem,
               ie.local_armazenamento,
               a.criado_em,
               ie.quantidade_atual,
               ie.quantidade_minima,
               ie.validade,
               CASE WHEN a.mensagem LIKE 'Estoque%' THEN 'ESTOQUE' ELSE 'VALIDADE' END AS categoria,
               ROW_NUMBER() OVER (
                   PARTITION BY a.item_estoque_id,
                                CASE WHEN a.mensagem LIKE 'Estoque%' THEN 'ESTOQUE' ELSE 'VALIDADE' END
                   ORDER BY a.criado_em DESC, a.id DESC
               ) AS ordem
          FROM alertas a
          JOIN itens_estoque ie ON ie.id = a.item_estoque_id
          JOIN hospitais h      ON h.id  = ie.hospital_id
         WHERE a.criado_em >= TRUNC(SYSDATE)
       )
 WHERE ordem = 1
   AND (
           (categoria = 'ESTOQUE'
            AND tipo = CASE
                           WHEN quantidade_atual <= quantidade_minima       THEN 'CRITICO'
                           WHEN quantidade_atual <= quantidade_minima * 1.5 THEN 'ATENCAO'
                       END)
        OR (categoria = 'VALIDADE' AND mensagem LIKE 'Item vencido%'
            AND validade < TRUNC(SYSDATE))
        OR (categoria = 'VALIDADE' AND mensagem LIKE 'Validade proxima%'
            AND validade BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + 60)
       );

CREATE OR REPLACE FUNCTION fn_dias_cobertura_estoque (
    p_item_id IN itens_estoque.id%TYPE
) RETURN NUMBER
IS
    v_quantidade_atual   itens_estoque.quantidade_atual%TYPE;
    v_consumo_medio_mes  NUMBER;
BEGIN
    SELECT quantidade_atual
      INTO v_quantidade_atual
      FROM itens_estoque
     WHERE id = p_item_id;

    SELECT NVL(AVG(quantidade_consumida), 0)
      INTO v_consumo_medio_mes
      FROM historico_consumo
     WHERE item_estoque_id = p_item_id
       AND mes_referencia >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6);

    IF v_consumo_medio_mes = 0 THEN
        RETURN NULL;
    END IF;

    RETURN ROUND(v_quantidade_atual / (v_consumo_medio_mes / 30), 1);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20101, 'Item de estoque ' || p_item_id || ' nao encontrado.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20109, 'Erro ao calcular dias de cobertura do item ' ||
                                        p_item_id || ': ' || SQLERRM);
END fn_dias_cobertura_estoque;
/

CREATE OR REPLACE FUNCTION fn_status_estoque_formatado (
    p_item_id IN itens_estoque.id%TYPE
) RETURN VARCHAR2
IS
    v_nome        itens_estoque.nome%TYPE;
    v_qtd_atual   itens_estoque.quantidade_atual%TYPE;
    v_qtd_minima  itens_estoque.quantidade_minima%TYPE;
    v_unidade     itens_estoque.unidade_medida%TYPE;
    v_validade    itens_estoque.validade%TYPE;
    v_hospital    hospitais.nome%TYPE;
    v_nivel       VARCHAR2(10);
    v_dias_venc   NUMBER;
    v_resultado   VARCHAR2(400);
BEGIN
    SELECT ie.nome, ie.quantidade_atual, ie.quantidade_minima,
           NVL(ie.unidade_medida, 'un.'), ie.validade, h.nome
      INTO v_nome, v_qtd_atual, v_qtd_minima, v_unidade, v_validade, v_hospital
      FROM itens_estoque ie
      JOIN hospitais h ON h.id = ie.hospital_id
     WHERE ie.id = p_item_id;

    IF v_qtd_atual <= v_qtd_minima THEN
        v_nivel := 'CRITICO';
    ELSIF v_qtd_atual <= v_qtd_minima * 1.5 THEN
        v_nivel := 'ATENCAO';
    ELSE
        v_nivel := 'NORMAL';
    END IF;

    v_resultado := '[' || v_nivel || '] ' || v_nome || ' (' || v_hospital || ') - ' ||
                   v_qtd_atual || ' ' || v_unidade || ' (min. ' || v_qtd_minima || ')';

    IF v_validade IS NOT NULL THEN
        v_dias_venc := TRUNC(v_validade) - TRUNC(SYSDATE);
        IF v_dias_venc < 0 THEN
            v_resultado := v_resultado || ' - VENCIDO em ' || TO_CHAR(v_validade, 'DD/MM/YYYY');
        ELSIF v_dias_venc <= 60 THEN
            v_resultado := v_resultado || ' - vence em ' || v_dias_venc || ' dia(s)';
        END IF;
    END IF;

    RETURN v_resultado;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Item de estoque ' || p_item_id || ' nao encontrado.';
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20108, 'Erro ao formatar status do item ' ||
                                        p_item_id || ': ' || SQLERRM);
END fn_status_estoque_formatado;
/

CREATE OR REPLACE PROCEDURE prc_registrar_alertas_criticos (
    p_hospital_id    IN  itens_estoque.hospital_id%TYPE DEFAULT NULL,
    p_total_alertas  OUT NUMBER
)
IS
    CURSOR c_itens IS
        SELECT ie.id, ie.nome, ie.quantidade_atual, ie.quantidade_minima,
               NVL(ie.unidade_medida, 'un.') AS unidade,
               ie.validade, ie.hospital_id, ie.local_armazenamento
          FROM itens_estoque ie
         WHERE p_hospital_id IS NULL
            OR ie.hospital_id = p_hospital_id;

    v_nivel          VARCHAR2(10);
    v_dias_venc      NUMBER;
    v_total_alertas  PLS_INTEGER := 0;

    PROCEDURE registrar_se_novo (
        p_item_id   IN alertas.item_estoque_id%TYPE,
        p_hosp_id   IN alertas.hospital_id%TYPE,
        p_tipo      IN alertas.tipo%TYPE,
        p_mensagem  IN alertas.mensagem%TYPE,
        p_origem    IN alertas.origem%TYPE
    ) IS
        v_ja_registrado NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_ja_registrado
          FROM alertas
         WHERE item_estoque_id = p_item_id
           AND tipo = p_tipo
           AND mensagem = p_mensagem
           AND criado_em >= TRUNC(SYSDATE);

        IF v_ja_registrado = 0 THEN
            INSERT INTO alertas (item_estoque_id, hospital_id, tipo, mensagem, origem)
            VALUES (p_item_id, p_hosp_id, p_tipo, p_mensagem, p_origem);
            v_total_alertas := v_total_alertas + 1;
        END IF;
    END registrar_se_novo;
BEGIN
    FOR r_item IN c_itens LOOP
        BEGIN
            IF r_item.quantidade_atual <= r_item.quantidade_minima THEN
                v_nivel := 'CRITICO';
            ELSIF r_item.quantidade_atual <= r_item.quantidade_minima * 1.5 THEN
                v_nivel := 'ATENCAO';
            ELSE
                v_nivel := NULL;
            END IF;

            IF v_nivel IS NOT NULL THEN
                registrar_se_novo(
                    r_item.id, r_item.hospital_id, v_nivel,
                    'Estoque ' || LOWER(v_nivel) || ': ' || r_item.quantidade_atual || ' ' ||
                    r_item.unidade || ' (minimo ' || r_item.quantidade_minima || ') - ' || r_item.nome,
                    r_item.local_armazenamento);
            END IF;

            IF r_item.validade IS NOT NULL THEN
                v_dias_venc := TRUNC(r_item.validade) - TRUNC(SYSDATE);

                IF v_dias_venc < 0 THEN
                    registrar_se_novo(
                        r_item.id, r_item.hospital_id, 'CRITICO',
                        'Item vencido em ' || TO_CHAR(r_item.validade, 'DD/MM/YYYY') || ' - ' || r_item.nome,
                        r_item.local_armazenamento);
                ELSIF v_dias_venc <= 60 THEN
                    registrar_se_novo(
                        r_item.id, r_item.hospital_id,
                        CASE WHEN v_dias_venc <= 15 THEN 'ATENCAO' ELSE 'INFO' END,
                        'Validade proxima: vence em ' || v_dias_venc || ' dia(s) - ' || r_item.nome,
                        r_item.local_armazenamento);
                END IF;
            END IF;

        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Falha ao processar item ' || r_item.id || ': ' || SQLERRM);
        END;
    END LOOP;

    p_total_alertas := v_total_alertas;
    DBMS_OUTPUT.PUT_LINE(v_total_alertas || ' alerta(s) novo(s) registrado(s).');

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20110, 'Erro ao registrar alertas criticos: ' || SQLERRM);
END prc_registrar_alertas_criticos;
/

CREATE OR REPLACE PROCEDURE prc_relatorio_consumo_hospital (
    p_hospital_id      IN  hospitais.id%TYPE,
    p_mes_referencia   IN  DATE,
    p_total_itens      OUT NUMBER,
    p_total_consumido  OUT NUMBER,
    p_custo_total      OUT NUMBER,
    p_cursor           OUT SYS_REFCURSOR
)
IS
    v_existe  NUMBER;
    e_hospital_inexistente EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO v_existe FROM hospitais WHERE id = p_hospital_id;
    IF v_existe = 0 THEN
        RAISE e_hospital_inexistente;
    END IF;

    SELECT COUNT(DISTINCT hc.item_estoque_id),
           NVL(SUM(hc.quantidade_consumida), 0),
           NVL(SUM(ROUND(hc.quantidade_consumida * NVL(ie.custo_unitario, 0), 2)), 0)
      INTO p_total_itens, p_total_consumido, p_custo_total
      FROM historico_consumo hc
      JOIN itens_estoque ie ON ie.id = hc.item_estoque_id
     WHERE hc.hospital_id = p_hospital_id
       AND TRUNC(hc.mes_referencia, 'MM') = TRUNC(p_mes_referencia, 'MM');

    OPEN p_cursor FOR
        SELECT ie.nome                                                       AS item,
               hc.quantidade_consumida                                       AS quantidade,
               NVL(ie.unidade_medida, 'un.')                                 AS unidade,
               ie.custo_unitario                                             AS custo_unitario,
               ROUND(hc.quantidade_consumida * NVL(ie.custo_unitario, 0), 2) AS custo_total
          FROM historico_consumo hc
          JOIN itens_estoque ie ON ie.id = hc.item_estoque_id
         WHERE hc.hospital_id = p_hospital_id
           AND TRUNC(hc.mes_referencia, 'MM') = TRUNC(p_mes_referencia, 'MM')
         ORDER BY hc.quantidade_consumida DESC;

EXCEPTION
    WHEN e_hospital_inexistente THEN
        RAISE_APPLICATION_ERROR(-20120, 'Hospital ' || p_hospital_id || ' nao encontrado.');
    WHEN OTHERS THEN
        IF p_cursor%ISOPEN THEN
            CLOSE p_cursor;
        END IF;
        RAISE_APPLICATION_ERROR(-20121, 'Erro ao gerar relatorio de consumo do hospital ' ||
                                        p_hospital_id || ': ' || SQLERRM);
END prc_relatorio_consumo_hospital;
/



PROMPT Objetos da Parte 3: esperado VALID
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('ALERTAS', 'VW_ALERTAS_VIGENTES',
                       'FN_DIAS_COBERTURA_ESTOQUE', 'FN_STATUS_ESTOQUE_FORMATADO',
                       'PRC_REGISTRAR_ALERTAS_CRITICOS', 'PRC_RELATORIO_CONSUMO_HOSPITAL')
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

